export type Language = 'th' | 'en';

export const languages = {
  th: {
    // Navigation & General
    appTitle: 'NovelTrans',
    translateNovel: 'แปลนิยาย',
    bin: 'ถังขยะ',
    admin: 'ผู้ดูแลระบบ',
    login: 'เข้าสู่ระบบ',
    logout: 'ออกจากระบบ',
    profile: 'โปรไฟล์',
    history: 'ประวัติการแปล',
    online: 'ออนไลน์',
    offline: 'ออฟไลน์',
    back: 'ย้อนกลับ',
    backToLibrary: 'กลับคลังนิยาย',
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    delete: 'ลบ',
    restore: 'กู้คืน',
    permanentDelete: 'ลบถาวร',
    loading: 'กำลังโหลด...',
    
    // Homepage
    heroBadge: 'AI Literary Translation Engine',
    heroTitle: 'คลังนิยายแปลไทยด้วย',
    heroDesc: 'ดึงเนื้อหาเว็บนิยายภาษาอังกฤษ แล้วแปลงเป็นสไตล์วรรณกรรมไทย อ่านลื่นไหลผ่าน Mobile PWA พร้อมระบบบันทึกอ่านแบบ Offline',
    searchPlaceholder: 'ค้นหาชื่อเรื่อง หรือผู้แต่ง...',
    latestNovels: 'รายการนิยายล่าสุด',
    loadingNovels: 'กำลังโหลดคลังนิยาย...',
    loadingNovelsSub: 'กรุณารอสักครู่ กำลังดึงรายการนิยายแปลไทย',
    noNovels: 'ยังไม่มีนิยายในคลัง',
    noNovelsDesc: 'กดปุ่ม + แปลนิยาย ที่ด้านบน เพื่อเริ่มวาง URL และดึงบทนิยายภาษาอังกฤษมาแปลไทยได้เลย!',
    readNow: 'อ่านเลย',
    noChapters: 'ไม่มีตอน',
    chaptersCount: 'ตอน',
    author: 'ผู้แต่ง',
    unknownAuthor: 'ไม่ระบุผู้แต่ง',
    loadingMore: 'กำลังโหลดนิยายเพิ่มเติม...',

    // Bin (Recycle Bin)
    recycleBinTitle: 'ถังขยะ (Recycle Bin)',
    recycleBinDesc: 'รายการที่ถูกลบชั่วคราว สามารถกดกู้คืนกลับมาหรือลบถาวรได้ที่นี่',
    viewList: 'รายการ',
    viewCard: 'การ์ด',
    selectAll: 'เลือกทั้งหมด',
    deselectAll: 'ยกเลิกเลือกทั้งหมด',
    selectedItemsCount: 'เลือกอยู่',
    itemsUnit: 'รายการ',
    restoreSelected: 'กู้คืนที่เลือก',
    permanentDeleteSelected: 'ลบถาวรที่เลือก',
    emptyBin: 'ถังขยะว่างเปล่า',
    emptyBinDesc: 'ไม่มีรายการนิยายหรือบทนิยายถูกย้ายมาที่นี่',
    novelsInBin: 'นิยายในถังขยะ',
    chaptersInBin: 'บทนิยายในถังขยะ',
    novelStoryPrefix: 'เรื่อง:',

    // Confirmation Modals
    confirmPermanentDeleteSingleTitle: 'ลบถาวร',
    confirmPermanentDeleteSingleMsg: 'คำเตือน: การลบนี้จะเป็นการลบออกจากระบบถาวร ไม่สามารถกู้คืนกลับมาได้อีก คุณแน่ใจหรือไม่?',
    confirmPermanentDeleteBatchTitle: 'ลบถาวรรายการที่เลือก',
    confirmPermanentDeleteBatchMsg: 'คำเตือน: คุณกำลังจะลบรายการที่เลือกทั้งหมดออกจากระบบอย่างถาวร ข้อมูลจะไม่สามารถกู้คืนได้อีกต่อไป คุณแน่ใจหรือไม่?',
    confirmDeleteButton: 'ยืนยันลบออกจากระบบถาวร',

    // Scrape Drawer
    drawerTitle: 'แปลนิยายเรื่องใหม่',
    drawerDesc: 'วาง URL หน้าสารบัญ หรือหน้าบทนิยายภาษาอังกฤษ เพื่อเริ่มดึงและแปลไทยทันที',
    urlInputLabel: 'URL เว็บนิยายต้นฉบับ',
    urlPlaceholder: 'เช่น https://www.royalroad.com/fiction/... หรือ /chapter/...',
    modeAuto: 'ตรวจจับอัตโนมัติ (แนะนำ)',
    modeSingle: 'แปลเฉพาะตอนนี้ (1 ตอน)',
    modeFull: 'ดึงและแปลทั้งเรื่อง (Batch Translation)',
    startTranslation: 'เริ่มดึงและแปลเนื้อหา',
    translatingState: 'กำลังแปลเนื้อหา...',
  },
  en: {
    // Navigation & General
    appTitle: 'NovelTrans',
    translateNovel: 'Translate',
    bin: 'Trash',
    admin: 'Admin',
    login: 'Log In',
    logout: 'Log Out',
    profile: 'Profile',
    history: 'History',
    online: 'Online',
    offline: 'Offline',
    back: 'Back',
    backToLibrary: 'Back to Library',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    restore: 'Restore',
    permanentDelete: 'Delete Permanently',
    loading: 'Loading...',
    
    // Homepage
    heroBadge: 'AI Literary Translation Engine',
    heroTitle: 'Web Novel Translation by',
    heroDesc: 'Scrape English web novels and transform them into Thai literary prose. Smooth reading via Mobile PWA with offline caching.',
    searchPlaceholder: 'Search titles or authors...',
    latestNovels: 'Latest Novels',
    loadingNovels: 'Loading library...',
    loadingNovelsSub: 'Please wait, fetching novel list',
    noNovels: 'No novels in library',
    noNovelsDesc: 'Click "+ Translate" button above to paste a URL and start translating English novels into Thai!',
    readNow: 'Read Now',
    noChapters: 'No chapters',
    chaptersCount: 'chs',
    author: 'Author',
    unknownAuthor: 'Unknown Author',
    loadingMore: 'Loading more novels...',

    // Bin (Recycle Bin)
    recycleBinTitle: 'Recycle Bin',
    recycleBinDesc: 'Soft-deleted items. You can restore them or permanently delete them here.',
    viewList: 'List',
    viewCard: 'Card',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    selectedItemsCount: 'Selected',
    itemsUnit: 'items',
    restoreSelected: 'Restore Selected',
    permanentDeleteSelected: 'Delete Selected',
    emptyBin: 'Trash is empty',
    emptyBinDesc: 'No novels or chapters in trash.',
    novelsInBin: 'Deleted Novels',
    chaptersInBin: 'Deleted Chapters',
    novelStoryPrefix: 'Novel:',

    // Confirmation Modals
    confirmPermanentDeleteSingleTitle: 'Permanent Delete',
    confirmPermanentDeleteSingleMsg: 'Warning: This will permanently delete this item. It cannot be recovered. Are you sure?',
    confirmPermanentDeleteBatchTitle: 'Delete Selected Items',
    confirmPermanentDeleteBatchMsg: 'Warning: You are about to permanently delete all selected items. This cannot be undone. Are you sure?',
    confirmDeleteButton: 'Confirm Permanent Delete',

    // Scrape Drawer
    drawerTitle: 'Translate New Novel',
    drawerDesc: 'Paste English table-of-contents or chapter URL to start scraping and translating.',
    urlInputLabel: 'Source Novel URL',
    urlPlaceholder: 'e.g. https://www.royalroad.com/fiction/... or /chapter/...',
    modeAuto: 'Auto Detect (Recommended)',
    modeSingle: 'Translate Single Chapter',
    modeFull: 'Full Novel (Batch Background)',
    startTranslation: 'Start Scraping & Translating',
    translatingState: 'Translating content...',
  },
} as const;

export type TranslationKey = keyof typeof languages.th;
