export type Language = 'th' | 'en';

export const languages = {
  th: {
    // Navigation & General
    appTitle: 'Tnovel',
    appDesc: 'นิยายแปลตามใจ',
    translateNovel: 'แปลนิยาย',
    bin: 'ถังขยะ',
    admin: 'ผู้ดูแลระบบ',
    login: 'เข้าสู่ระบบ',
    logout: 'ออกจากระบบ',
    profile: 'โปรไฟล์',
    history: 'ประวัติการแปล',
    bookshelf: 'ชั้นหนังสือ',
    myBookshelf: 'ชั้นหนังสือของฉัน',
    library: 'คลังนิยาย',
    home: 'หน้าแรก',
    online: 'ออนไลน์',
    offline: 'ออฟไลน์',
    back: 'ย้อนกลับ',
    backToLibrary: 'กลับคลังนิยาย',
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    delete: 'ลบ',
    restore: 'กู้คืน',
    permanentDelete: 'ลบถาวร',
    loading: 'กำลังโหลด...',
    guest: 'ผู้เยี่ยมชม (Guest)',
    chapterPrefix: 'ตอนที่',

    // Themes & Language Switcher
    themeLabel: 'ธีมปัจจุบัน: ',
    themeDark: 'มืด (Dark)',
    themeLight: 'สว่าง (Light)',
    themeSepia: 'ถนอมสายตา (Sepia)',
    switchToEn: 'Switch to English',
    switchToTh: 'เปลี่ยนเป็นภาษาไทย',

    // Homepage
    heroBadge: 'AI Literary Translation Engine',
    heroTitle: 'คลังนิยายแปลไทย',
    heroDesc: 'ดึงเนื้อหาเว็บนิยายภาษาอังกฤษ แล้วแปลงเป็นสไตล์วรรณกรรมไทย อ่านลื่นไหลผ่าน Mobile PWA พร้อมระบบบันทึกอ่านแบบ Offline',
    searchPlaceholder: 'ค้นหาชื่อเรื่อง หรือผู้แต่ง...',
    latestNovels: 'รายการนิยายล่าสุด',
    recentReadingTitle: 'การอ่านล่าสุด',
    recentReadingCount: 'เรื่อง',
    noRecentReading: 'ไม่มีประวัติการอ่าน',
    btnContinueReadingShort: 'อ่านต่อ',
    scrollLeft: 'เลื่อนซ้าย',
    scrollRight: 'เลื่อนขวา',
    loadingNovels: 'กำลังโหลดคลังนิยาย...',
    loadingNovelsSub: 'กรุณารอสักครู่ กำลังดึงรายการนิยายแปลไทย',
    connectingLibrary: 'กำลังเชื่อมต่อคลังนิยาย...',
    connectingLibrarySub: 'กรุณารอสักครู่ กำลังเชื่อมต่อระบบ',
    noNovels: 'ยังไม่มีนิยายในคลัง',
    noNovelsDesc: 'กดปุ่ม + แปลนิยาย ที่ด้านบน เพื่อเริ่มวาง URL และดึงบทนิยายภาษาอังกฤษมาแปลไทยได้เลย!',
    readNow: 'อ่านเลย',
    noChapters: 'ไม่มีตอน',
    chaptersCount: 'ตอน',
    author: 'ผู้แต่ง',
    unknownAuthor: 'ไม่ระบุผู้แต่ง',
    loadingMore: 'กำลังโหลดนิยายเพิ่มเติม...',
    allNovelsLoaded: 'แสดงนิยายทั้งหมดแล้ว',
    selectCategory: 'เลือกหมวดหมู่นิยาย (บังคับเลือก)*',
    categoryLabel: 'หมวดหมู่นิยาย',
    categoryRequiredNotice: 'กรุณาเลือกหมวดหมู่นิยายก่อนเริ่มแปล',
    allCategories: 'ทุกหมวดหมู่',

    // Novel Card
    translating: 'กำลังแปล...',
    moveToBin: 'ย้ายลงถังขยะ',
    confirmMoveToBinTitle: 'ย้ายนิยายลงถังขยะ',
    confirmMoveToBinMsg: 'คุณต้องการย้ายนิยายเรื่องนี้และบทนิยายทั้งหมดลงถังขยะใช่หรือไม่? (สามารถกู้คืนกลับมาได้ทุกเมื่อในหน้าถังขยะ)',
    addedBy: 'เพิ่มโดย:',
    addedByTitle: 'เพิ่มเรื่องโดย: ',
    authorTitle: 'ผู้แต่ง: ',
    viewCountTitle: 'ยอดเปิดอ่าน ',
    timesUnit: ' ครั้ง',
    fromTotal: ' จาก ',
    inBookshelfTooltip: 'อยู่ในชั้นหนังสือแล้ว (กดเพื่อนำออก)',
    addToBookshelfTooltip: 'เพิ่มเข้าชั้นหนังสือ',
    likedTooltip: 'ยกเลิกถูกใจ',
    likeTooltip: 'กดถูกใจ',

    // Novel Detail Page
    novelDetailPageTitle: 'ข้อมูลนิยายและสารบัญ',
    startReadingFirstChapter: 'เริ่มอ่านตอนแรก',
    readFirstChapter: 'อ่านตอนที่ 1',
    continueReadingChapter: 'อ่านต่อ',
    continueReadingFrom: 'อ่านต่อจาก',
    novelSynopsis: 'เรื่องย่อ',
    noSynopsis: 'ยังไม่มีข้อมูลเรื่องย่อของนิยายเรื่องนี้',
    readMoreSynopsis: 'อ่านเพิ่มเติม',
    readLessSynopsis: 'ย่อลง',
    novelInfo: 'ข้อมูลนิยาย',
    sortOldestFirst: 'ตอนแรกสุด',
    sortNewestFirst: 'ตอนล่าสุด',
    totalChaptersInNovel: 'จำนวนตอนทั้งหมด',
    sourceOriginal: 'เว็บต้นฉบับ',
    viewOriginalSource: 'ดูเว็บต้นฉบับ',
    shareNovel: 'แชร์นิยาย',
    copiedLinkToast: 'คัดลอกลิงก์เรื่องนี้แล้ว',
    statusTranslating: 'กำลังแปล',
    publishedDate: 'เพิ่มเข้าระบบเมื่อ',
    lastUpdatedDate: 'อัปเดตล่าสุด',
    tableOfContentsForNovel: 'สารบัญบทนิยาย',
    filterChaptersPlaceholder: 'ค้นหาเลขตอน หรือชื่อบท...',
    noChaptersFoundFilter: 'ไม่พบบทนิยายที่ค้นหา',
    lastReadBadge: 'อ่านค้างไว้',
    shareNovelSuccess: 'แชร์เรียบร้อย',
    backToHome: 'กลับหน้าหลัก',
    chaptersInNovelCount: 'บท',

    // Bin (Recycle Bin)
    recycleBinTitle: 'ถังขยะ (Recycle Bin)',
    recycleBinDesc: 'รายการที่ถูกลบชั่วคราว สามารถกดกู้คืนกลับมาหรือลบถาวรได้ที่นี่',
    viewList: 'รายการ',
    viewCard: 'การ์ด',
    selectAll: 'เลือกทั้งหมด',
    deselectAll: 'ยกเลิกเลือกทั้งหมด',
    selectedItemsCount: 'เลือกอยู่',
    itemsUnit: 'รายการ',
    restoreSelected: 'กู้คืนที่เลือก',
    permanentDeleteSelected: 'ลบถาวรที่เลือก',
    emptyBin: 'ถังขยะว่างเปล่า',
    emptyBinDesc: 'ไม่มีรายการนิยายหรือบทนิยายถูกย้ายมาที่นี่',
    novelsInBin: 'นิยายในถังขยะ',
    chaptersInBin: 'บทนิยายในถังขยะ',
    novelStoryPrefix: 'เรื่อง:',

    // Confirmation Modals
    confirmPermanentDeleteSingleTitle: 'ลบถาวร',
    confirmPermanentDeleteSingleMsg: 'คำเตือน: การลบนี้จะเป็นการลบออกจากระบบถาวร ไม่สามารถกู้คืนกลับมาได้อีก คุณแน่ใจหรือไม่?',
    confirmPermanentDeleteBatchTitle: 'ลบถาวรรายการที่เลือก',
    confirmPermanentDeleteBatchMsg: 'คำเตือน: คุณกำลังจะลบรายการที่เลือกทั้งหมดออกจากระบบอย่างถาวร ข้อมูลจะไม่สามารถกู้คืนได้อีกต่อไป คุณแน่ใจหรือไม่?',
    confirmDeleteButton: 'ยืนยันลบออกจากระบบถาวร',
    confirmModalSoftDeleteTitle: 'ยืนยันการย้ายไปยังถังขยะ',
    confirmModalSoftDeleteMsg: 'คุณต้องการย้ายรายการนี้ไปยังถังขยะใช่หรือไม่? คุณสามารถกู้คืนรายการนี้ได้ตลอดเวลาในหน้าถังขยะ (Recycle Bin)',
    confirmModalSoftDeleteNote: 'การลบนี้เป็น Soft Delete สามารถกู้คืนได้',

    // Scrape Drawer
    drawerTitle: 'แปลนิยายเรื่องใหม่',
    drawerDesc: 'วาง URL หน้าสารบัญ หรือหน้าบทนิยาย (Dek-D, RoyalRoad, FanMTL ฯลฯ) เพื่อเริ่มดึงและนำเข้าทันที',
    urlInputLabel: 'URL เว็บนิยายต้นฉบับ',
    urlPlaceholder: 'เช่น https://www.royalroad.com/... หรือ https://writer.dek-d.com/...',
    modeAuto: 'ตรวจจับอัตโนมัติ (แนะนำ)',
    modeSingle: 'แปลหรือนำเข้าเฉพาะตอนนี้ (1 ตอน)',
    modeFull: 'ดึงและแปล/นำเข้าทั้งเรื่อง',
    startTranslation: 'เริ่มดึงและแปลเนื้อหา',
    translatingState: 'กำลังแปลเนื้อหา...',
    drawerAddNovel: 'เพิ่มนิยาย / นำเข้า',
    drawerTabUrlSub: 'ดึงจาก URL เว็บนิยาย (Dek-D, RoyalRoad, FanMTL ฯลฯ)',
    drawerTabPasteSub: 'วางเนื้อหาตอนที่คัดลอกมาเอง (รองรับทั้งไทยและอังกฤษ)',
    tabFromUrl: 'จาก URL',
    tabPasteSelf: 'แปะเนื้อหาเอง',
    statusDone: 'เสร็จสิ้น',
    pasteNovelTitleLabel: 'ชื่อเรื่อง',
    pasteNovelTitlePlaceholder: 'เลือกเรื่องเดิม หรือพิมพ์ชื่อเรื่องใหม่',
    pasteNovelTitleHint: 'ชื่อตรงกับเรื่องที่มีอยู่ = เพิ่มเป็นตอนถัดไปของเรื่องนั้น',
    pasteChapterTitleLabel: 'ชื่อตอน (ไม่ใส่ก็ได้)',
    pasteChapterTitlePlaceholder: 'เช่น ตอนที่ 1: ... หรือ Chapter 1',
    pasteContentLabel: 'เนื้อหาต้นฉบับ (รองรับทั้งภาษาไทยและอังกฤษ)',
    pasteContentPlaceholder: 'วางเนื้อหาตอนที่นี่ เว้นบรรทัดว่างระหว่างย่อหน้า',
    charCount: 'ตัวอักษร',
    noContentYet: 'ยังไม่มีเนื้อหา',
    thaiDetectedNotice: '🇹🇭 ตรวจพบภาษาไทย: จะนำเข้าเนื้อหาต้นฉบับโดยตรงโดยไม่แปล',
    btnTranslateAndSave: 'นำเข้า / แปลและบันทึกตอนใหม่',
    scrapeModeLabel: 'โหมดการดึงข้อมูล',
    scrapeFullNovel: 'ดึงทั้งเรื่องจากหน้าหลัก/สารบัญ',
    scrapeSingleChapter: 'ดึงเฉพาะตอนนี้',
    translationQualityLabel: 'คุณภาพการแปล',
    qualityFast: 'แปลเร็ว (Google Translate)',
    qualityFastDesc: 'เร็วมาก (~1-2 วินาที/ตอน)',
    qualityPolished: 'แปลคุณภาพ (Google + AI เกลาสำนวน)',
    qualityPolishedDesc: 'สละสลวย ภาษาวรรณกรรมลื่นไหล',
    scrapeUrlInputLabel: 'URL หน้าหลักนิยาย หรือ URL บทนิยาย',
    btnStartScrapeAndTranslate: 'เริ่มต้นดึงและนำเข้าเนื้อหา',
    sampleUrlsLabel: 'ตัวอย่างลิงก์นิยายสำหรับทดลอง:',
    sampleFullTitle: 'RoyalRoad (นิยายแปลอังกฤษทั้งเรื่อง)',
    sampleDekDTitle: 'Dek-D เด็กดี (นิยายไทยทั้งเรื่อง)',
    sampleSingleTitle: 'ตอนเฉพาะ (Single Chapter)',

    // History Page
    historyTitle: 'ประวัติการแปลนิยาย',
    historySubTitle: 'รายการนิยายที่นำเข้าและแปลด้วย AI',
    historyDesc: 'จัดการนิยายที่นำเข้า ตรวจสอบสถานะการแปล และกดแปลบทที่เหลือต่อได้ทันที',
    btnTranslateNew: 'แปลเรื่องใหม่',
    filterAll: 'ทั้งหมด',
    filterTranslating: 'กำลังแปล / พักไว้',
    filterCompleted: 'แปลเสร็จแล้ว',
    historySearchPlaceholder: 'ค้นหาชื่อเรื่อง / ผู้แต่ง...',
    historyLoading: 'กำลังโหลดประวัติการแปลนิยาย...',
    historyEmpty: 'ไม่พบประวัติการแปลนิยาย',
    historyEmptyTranslating: 'ไม่มีนิยายที่กำลังแปลหรือพักค้างไว้',
    historyEmptyCompleted: 'ยังไม่มีนิยายที่แปลครบสมบูรณ์',
    historyEmptyAll: 'คุณยังไม่ได้นำเข้านิยายเรื่องใดมาแปล',
    btnStartFirstNovel: 'เริ่มแปลนิยายเรื่องแรก',
    statusCompleted: 'แปลสมบูรณ์แล้ว',
    statusPaused: 'พักไว้ / รอแปลต่อ',
    translatedCountLabel: 'แปลเสร็จ: ',
    resumeTranslateTooltip: 'เริ่มดึงและแปลบทที่เหลือต่อ',
    btnResume: 'แปลต่อ',
    btnReadNovel: 'อ่านนิยาย',
    openOriginalWebTooltip: 'เปิดเว็บต้นฉบับ',
    resumeError: 'เกิดข้อผิดพลาดในการเริ่มแปลต่อ',

    // Bookshelf Page
    bookshelfSyncAccount: 'บันทึกเชื่อมต่อกับบัญชีของคุณ',
    bookshelfGuestMode: 'โหมดทั่วไป (บันทึกในเครื่องนี้)',
    tabFollowing: 'กำลังติดตาม',
    tabReadingHistory: 'ประวัติการอ่าน',
    tabBookmarks: 'คั่นหน้า',
    bookshelfLoading: 'กำลังโหลดข้อมูลชั้นหนังสือ...',
    bookshelfEmpty: 'ยังไม่มีนิยายในชั้นหนังสือ',
    bookshelfEmptyDesc: 'กดปุ่มไอคอนบุ๊กมาร์กบนการ์ดนิยายเรื่องที่คุณสนใจ เพื่อเพิ่มเข้าชั้นหนังสือและติดตามตอนใหม่ได้ที่นี่',
    btnBrowseNovels: 'ค้นหานิยายอ่าน',
    newChaptersNotice: 'มีตอนใหม่ ',
    removeFromBookshelfTooltip: 'นำออกจากชั้นหนังสือ',
    notStartedReading: 'ยังไม่ได้เริ่มอ่าน',
    totalChaptersLabel: 'ทั้งหมด ',
    btnContinueReading: 'อ่านต่อจากที่ค้างไว้',
    btnStartFirstChapter: 'เริ่มอ่านตอนแรก',
    noTranslatedChaptersYet: 'ยังไม่มีตอนที่แปลเสร็จ',
    historyTabDesc: 'แสดงนิยายที่คุณเคยเปิดอ่าน เรียงจากล่าสุด',
    btnClearHistory: 'ล้างประวัติทั้งหมด',
    historyEmptyTitle: 'ยังไม่มีประวัติการอ่าน',
    historyEmptyDesc: 'เมื่อคุณเริ่มเปิดอ่านนิยายตอนใด ระบบจะบันทึกประวัติและจุดที่อ่านค้างไว้ให้อัตโนมัติที่นี่',
    readUpTo: 'อ่านถึง ',
    readPercent: 'อ่านแล้ว ',
    deleteFromHistoryTooltip: 'ลบออกจากประวัติ',
    btnReadContinue: 'อ่านต่อ',
    bookmarksTabDesc: 'รายการบทนิยายที่คุณกดคั่นหน้าไว้ เพื่อกลับมาอ่านตอนสำคัญได้ตลอดเวลา',
    bookmarksEmptyTitle: 'ยังไม่มีบุ๊กมาร์กคั่นหน้า',
    bookmarksEmptyDesc: 'ขณะอ่านนิยาย สามารถกดปุ่มฟันเฟือง ⚙️ แล้วเลือก "คั่นหน้านี้" เพื่อบันทึกตอนที่คุณชอบไว้ที่นี่ได้',
    bookmarkedAt: 'คั่นเมื่อ ',
    removeBookmarkTooltip: 'ยกเลิกบุ๊กมาร์ก',
    btnOpenChapter: 'เปิดอ่าน',
    timeJustNow: 'เมื่อสักครู่',
    timeMinsAgo: 'นาทีที่แล้ว',
    timeHoursAgo: 'ชั่วโมงที่แล้ว',
    timeDaysAgo: 'วันที่แล้ว',

    // Reader View
    prevChapter: 'ตอนก่อนหน้า',
    nextChapter: 'ตอนต่อไป',
    tableOfContents: 'สารบัญ',
    selectChapterFromTocTooltip: 'เลือกตอนจากสารบัญ',
    checkNewChapter: 'เช็คตอนใหม่',
    checkNewChapterTooltip: 'ตรวจเช็คตอนใหม่ล่าสุด',
    newChapterToastReady: 'พร้อมให้อ่านต่อได้ทันที',
    newChapterToastDone: 'แปลเสร็จแล้ว!',
    tocTitle: 'สารบัญบทนิยาย',
    searchChapterPlaceholder: 'ค้นหาตามเลขตอน หรือชื่อบท...',
    chapterNotFound: 'ไม่พบบทนิยายที่ค้นหา',
    noChaptersInSystem: 'ยังไม่มีบทนิยายในระบบ',
    currentlyReading: 'กำลังอ่าน',
    readerSettingsTitle: 'การตั้งค่าหน้าอ่านนิยาย',
    displayModeLabel: 'โหมดแสดงภาษา',
    modeThLabel: 'แปลไทย (TH)',
    modeEnLabel: 'อังกฤษ (EN)',
    modeParallelLabel: 'คู่สองภาษา',
    themeColorLabel: 'ธีมสีการอ่าน',
    themeLightLabel: 'สว่าง (White)',
    themeSepiaLabel: 'ซีเปีย (Sepia)',
    themeDarkLabel: 'มืด (OLED)',
    fontSizeLabel: 'ขนาดฟอนต์',
    fontSm: 'เล็ก (14px)',
    fontMd: 'กลาง (16px)',
    fontLg: 'ใหญ่ (18px)',
    fontXl: 'ใหญ่พิเศษ',
    fontFamilyLabel: 'แบบอักษร (Font Family)',
    fontSans: 'ไม่มีหัว (Kanit / Sans)',
    fontSerif: 'มีหัว/วรรณกรรม (Sarabun)',
    chapterToolsLabel: 'เครื่องมือบทนิยาย',
    retranslateGoogle: 'แปลใหม่ (Google)',
    retranslateGoogleDesc: 'เร็ว ไม่จำกัดครั้ง',
    polishWithAI: 'เกลาสำนวน (AI)',
    polishWithAIDesc: 'เกลาคำแปลให้อ่านลื่นแบบวรรณกรรม',
    bookmarkCurrentChapter: 'คั่นหน้านี้ (บันทึกบุ๊กมาร์ก)',
    bookmarkedCurrentChapter: 'คั่นหน้านี้แล้ว (กดเพื่อยกเลิก)',
    reportChapterIssue: 'แจ้งปัญหาบทนิยายนี้ (แปลผิด / เนื้อหาขาด)',
    noPrevChapter: 'ไม่มีตอนก่อนหน้า',
    noNextChapter: 'ไม่มีตอนถัดไป',
    autoLoadingNextChapter: 'กำลังโหลดตอนถัดไปให้อัตโนมัติ...',
    reachedLatestChapter: 'คุณอ่านถึงตอนล่าสุดที่มีในระบบแล้ว',
    closeMenu: 'ปิดเมนู',
    retranslatedGoogleSuccess: 'แปลใหม่ด้วย Google Translate เรียบร้อย',
    polishSuccess: 'เกลาสำนวนวรรณกรรมสำเร็จแล้ว',
    polishPartial: 'เกลาได้บางส่วน (โควตา AI ไม่พอ) กดเกลาอีกครั้งภายหลังได้',
    alreadyPolished: 'บทนี้เกลาสำนวนไว้แล้ว',
    retranslateFailed: 'แปลใหม่ไม่สำเร็จ',

    // Bookshelf Toasts & Prompts
    historyItemRemovedToast: 'ลบรายการออกจากประวัติแล้ว',
    confirmClearHistoryMsg: 'ต้องการล้างประวัติการอ่านทั้งหมดหรือไม่?',
    historyClearedToast: 'ล้างประวัติการอ่านทั้งหมดแล้ว',
    bookmarkRemovedToast: 'ลบบุ๊กมาร์กเรียบร้อย',

    // Report Modal
    reportModalTitle: 'แจ้งปัญหานิยาย',
    reportModalSub: 'รายงานข้อผิดพลาดให้ Admin ทราบ',
    reportSuccessTitle: 'ส่งรายงานปัญหาเรียบร้อยแล้ว',
    reportSuccessDesc: 'ขอบคุณสำหรับการแจ้ง ทีมงานจะรีบตรวจสอบให้ครับ',
    reportReasonLabel: 'สาเหตุที่พบปัญหา',
    reportDescLabel: 'รายละเอียดเพิ่มเติม (ไม่บังคับ)',
    reportDescPlaceholder: 'ระบุข้อความหรือจุดที่แปลผิดพลาด...',
    reportSending: 'กำลังส่ง...',
    reportSubmit: 'ส่งรายงาน',
    reportReason1: 'เนื้อหาแปลผิดพลาด / อ่านไม่รู้เรื่อง',
    reportReason2: 'มีข้อความภาษาอังกฤษปน / แปลไม่ครบ',
    reportReason3: 'ตอนไม่สมบูรณ์ / ขาดหาย',
    reportReason4: 'ลิงก์ต้นฉบับเสีย / เข้าไม่ได้',
    reportReason5: 'ปัญหาอื่นๆ',
    reportErrorDefault: 'เกิดข้อผิดพลาดในการส่งรายงาน',
    networkError: 'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้',

    // Background Progress Widget
    widgetPaused: 'พักการแปล',
    widgetResume: 'แปลต่อ',
    widgetPause: 'พักการแปล',
    widgetClickToResume: 'กดเพื่อแปลต่อ',
    widgetClickToPause: 'กดเพื่อหยุดชั่วคราว',
    widgetMinimize: 'ย่อขนาด',
    widgetCancel: 'ยกเลิกการแปล',
    widgetCompleted: 'แปลครบเรียบร้อยแล้ว!',
    widgetPausedBadge: '⏸️ พักการแปลชั่วคราว',
    widgetSavedCount: 'บันทึกแล้ว ',
    widgetScanCount: 'สแกน ',
    widgetCancelConfirmTitle: 'ยืนยันยกเลิกการแปล?',
    widgetCancelConfirmMsg: 'คุณต้องการยกเลิกการแปลเรื่อง',
    widgetCancelTip: '💡 ตอนที่แปลเสร็จแล้ว จะยังคงอยู่ และสามารถกลับมากดแปลต่อได้ตลอดเวลาในหน้า "ประวัติการแปล"',
    widgetConfirmCancelBtn: 'ยืนยันยกเลิกการแปล',
    widgetResumeBackBtn: 'แปลต่อ / ย้อนกลับ',

    // Bin Page
    viewListTooltip: 'แสดงแบบรายการ (List View)',
    viewCardTooltip: 'แสดงแบบการ์ด (Card View)',
    clearSelectionTooltip: 'ล้างการเลือก',
    restoreSingleTooltip: 'กู้คืน',
    permanentDeleteSingleTooltip: 'ลบถาวร',
    restoreSuccess: 'กู้คืนสำเร็จ',
    restoreError: 'เกิดข้อผิดพลาดในการกู้คืน',
    permanentDeleteSuccess: 'ลบถาวรเรียบร้อย',
    permanentDeleteError: 'เกิดข้อผิดพลาดในการลบถาวร',
    loadingBinItems: 'กำลังดึงรายการในถังขยะ...',
    connectionError: 'เกิดข้อผิดพลาดในการเชื่อมต่อ: ',

    // Author & Reader & Profile & Auth
    authorNotFound: 'ไม่พบข้อมูลผู้แต่งนี้',
    authorWorksCount: 'ผลงานในระบบ: ',
    authorAllWorks: 'ผลงานนิยายทั้งหมดของผู้แต่ง',
    authorNoNovels: 'ไม่พบนิยายของผู้แต่งรายนี้',
    loadingNovelContent: 'กำลังโหลดเนื้อหานิยาย...',
    loadChapterError: 'เกิดข้อผิดพลาดในการโหลดบทนิยาย',
    tryAgain: 'ลองใหม่อีกครั้ง',
    appStatusPwa: 'สถานะแอป: Mobile PWA พร้อมใช้งาน Offline',
    loginTitle: 'เข้าสู่ระบบ Tnovel',
    loginSubtitle: 'อ่านและแปลนิยายภาษาอังกฤษเป็นภาษาไทยสไตล์วรรณกรรม',
    loginWithGoogle: 'เข้าสู่ระบบด้วย Google',
    orDivider: 'หรือ',
    emailLabel: 'อีเมล',
    passwordLabel: 'รหัสผ่าน',
    nameLabel: 'ชื่อหรือนามแฝง',
    namePlaceholder: 'ชื่อของคุณ',
    passwordPlaceholder: 'อย่างน้อย 6 ตัวอักษร',
    loggingIn: 'กำลังเข้าสู่ระบบ...',
    noAccountYet: 'ยังไม่มีบัญชีผู้ใช้?',
    registerHere: 'ลงทะเบียนที่นี่',
    registerTitle: 'สมัครสมาชิกใหม่',
    registerSubtitle: 'สร้างบัญชีเพื่อบันทึกประวัติการอ่านและแปลนิยาย',
    continueWithGoogle: 'ดำเนินการต่อด้วย Google',
    registering: 'กำลังสมัครสมาชิก...',
    alreadyHaveAccount: 'มีบัญชีผู้ใช้อยู่แล้ว?',
    loginHere: 'เข้าสู่ระบบที่นี่',
    authAlertTitle: 'แจ้งเตือนระบบ',
    authErrorTitle: 'เกิดข้อผิดพลาดในการเข้าสู่ระบบ',
    btnUnderstand: 'ตกลง',
    adminDashboard: 'แดชบอร์ด Admin',

    // Scraper Drawer Statuses & Messages
    scrapeStatusCrawling: 'กำลังกวาดสายตาดึงรายชื่อบทนิยายทั้งหมดจากหน้าหลัก...',
    scrapeStatusFetching: 'กำลังดึงเนื้อหาจากเว็บนิยายต้นฉบับ...',
    scrapeStatusTranslating: 'กำลังวิเคราะห์และแปลบทนิยาย...',
    scrapeStatusTranslatingBatchesPrefix: 'กำลังแปลย่อหน้าชุดที่ ',
    scrapeStatusTranslatingBgPrefix: 'กำลังแอบแปลเบื้องหลังตอนที่ ',
    scrapeStatusComplete: 'แปลนิยายครบทั้งเรื่องเรียบร้อยแล้ว!',
    scrapeStatusRedirecting: 'แปลเรียบร้อยแล้ว! กำลังนำคุณไปยังหน้าอ่าน...',
    scrapeStatusInit: 'กำลังเริ่มต้นระบบดึงข้อมูล...',
    scrapeErrorServerDb: 'เกิดข้อผิดพลาดในการรับข้อมูลจากเซิร์ฟเวอร์ กรุณาตรวจสอบฐานข้อมูล',
    scrapeErrorStatusCode: 'เกิดข้อผิดพลาดรหัส ',
    scrapeSuccessRedirecting: 'เรียบร้อย! กำลังนำคุณไปยังหน้าอ่านนิยาย...',
    scrapeErrorFetch: 'เกิดข้อผิดพลาดในการดึงเนื้อหา',
    scrapeStatusPasting: 'กำลังแปลเนื้อหาที่วางไว้...',
    scrapeErrorServer: 'เกิดข้อผิดพลาดในการรับข้อมูลจากเซิร์ฟเวอร์',
    scrapeSuccessPasted: 'แปลเสร็จ ',
    scrapeSuccessPastedTail: ' ย่อหน้า กำลังเปิดหน้าอ่าน...',
    scrapeErrorAddChapter: 'เกิดข้อผิดพลาดในการเพิ่มตอน',

    // Admin Dashboard
    adminPageTitle: 'ระบบผู้ดูแลระบบ (Admin Dashboard)',
    adminPageDesc: 'จัดการผู้ใช้ คลังนิยายทั้งหมด และรายงานปัญหาจากผู้ใช้',
    socketConnected: 'เชื่อมต่อแล้ว',
    socketDisconnected: 'ไม่ได้เชื่อมต่อ',
    adminTabReports: 'รายงานปัญหา',
    adminTabNovels: 'จัดการนิยาย',
    adminTabUsers: 'จัดการผู้ใช้งาน',
    adminTabWhitelist: 'อีเมลที่อนุญาต (Whitelist)',
    adminLoading: 'กำลังโหลดข้อมูลระบบ Admin...',
    statusLabel: 'สถานะ:',
    filterPending: 'รอดำเนินการ',
    filterResolved: 'แก้ไขแล้ว',
    filterDismissed: 'ปฏิเสธ',
    refresh: 'รีเฟรช',
    noReportsTitle: 'ไม่มีรายงานปัญหาในหมวดหมู่นี้',
    noReportsDesc: 'ระบบทำงานราบรื่น ยังไม่มีผู้ใช้แจ้งปัญหาเข้ามา',
    reportLocationLabel: 'ตำแหน่งที่เกิดปัญหา:',
    generalNovel: 'นิยายทั่วไป',
    viewThisChapter: 'เปิดดูบทนิยายนี้',
    reportUserDetailLabel: 'รายละเอียดจากผู้ใช้:',
    noDescriptionProvided: 'ไม่ได้ระบุคำอธิบายเพิ่มเติม',
    reportedBy: 'ผู้แจ้ง: ',
    markAsResolved: 'ทำเครื่องหมายว่าแก้ไขแล้ว',
    dismissReport: 'ปฏิเสธ',
    deleteReportTooltip: 'ลบรายงานนี้',
    originalWebsite: 'เว็บต้นฉบับ',
    statusInBin: 'ในถังขยะ',
    statusActive: 'ใช้งานอยู่',
    moveToBinTooltip: 'ย้ายไปถังขยะ',
    usersListTitle: 'รายชื่อผู้ใช้งานในระบบ',
    userColNameEmail: 'ชื่อ / อีเมล',
    userColRole: 'สิทธิ์ (Role)',
    userColNovelsTranslated: 'แปลนิยายไปแล้ว',
    userColRegisteredDate: 'วันที่สมัคร',
    userColManageRole: 'จัดการสิทธิ์',
    userNoName: 'ไม่มีชื่อ',
    updating: 'กำลังอัปเดต...',
    demoteToUser: 'ปรับเป็น USER',
    promoteToAdmin: 'โปรโมตเป็น ADMIN',
    addWhitelistTitle: 'เพิ่มอีเมลที่อนุญาต (Add to Whitelist)',
    addWhitelistDesc: 'เฉพาะอีเมลที่อยู่ในรายชื่อนี้เท่านั้นจึงจะสามารถเข้าสู่ระบบหรือลงทะเบียนได้ (รวมถึง Google Login)',
    emailWhitelistPlaceholder: 'user@example.com หรือ user@gmail.com',
    emailNoteLabel: 'หมายเหตุ (Optional)',
    emailNotePlaceholder: 'เช่น บัญชีสำรอง, สมาชิกในทีม, เพื่อน',
    addEmailBtn: 'เพิ่มอีเมล',
    whitelistListTitle: 'รายชื่ออีเมลที่ได้รับอนุญาต',
    searchWhitelistPlaceholder: 'ค้นหาอีเมลหรือหมายเหตุ...',
    whitelistNotFound: 'ไม่พบอีเมลที่ตรงกับคำค้นหา',
    whitelistEmpty: 'ยังไม่มีอีเมลในระบบ Whitelist',
    whitelistColEmail: 'อีเมลที่อนุญาต',
    whitelistColNote: 'หมายเหตุ',
    whitelistColRole: 'ระดับสิทธิ์ (Role)',
    whitelistColAccountStatus: 'สถานะบัญชีในระบบ',
    whitelistColDate: 'วันที่อนุญาต',
    whitelistColAction: 'จัดการ',
    noNote: '- ไม่มี -',
    hasAccount: 'มีบัญชีแล้ว',
    notLoggedInYet: 'ยังไม่ได้เข้าสู่ระบบ',
    primaryAdmin: 'ผู้ดูแลหลัก',
    removeFromWhitelistTooltip: 'ลบออกจาก Whitelist (บล็อก)',
    whitelistAddSuccess: 'เพิ่มอีเมลเข้าสู่ Whitelist เรียบร้อยแล้ว',
    whitelistAddError: 'ไม่สามารถเพิ่มอีเมลได้',
    cannotDeletePrimaryAdmin: 'ไม่สามารถลบอีเมลผู้ดูแลระบบหลักได้',
    confirmDeleteWhitelistMsg: 'คุณแน่ใจหรือไม่ว่าต้องการลบอีเมลนี้ออกจาก Whitelist? (ผู้ใช้นี้จะไม่สามารถเข้าสู่ระบบได้)',
    deleteWhitelistError: 'เกิดข้อผิดพลาดในการลบอีเมล',
    thNovel: 'นิยาย',
    thAuthor: 'ผู้แต่ง',
    thChaptersCount: 'จำนวนตอน',
    thReports: 'รายงานปัญหา',
    thStatus: 'สถานะ',
    thAction: 'การจัดการ',
    reportsUnit: 'รายงาน',
    storiesUnit: 'เรื่อง',
    adminConsole: 'ระบบจัดการหลังบ้าน',
    adminBackToSite: 'กลับสู่หน้าเว็บหลัก',
    adminNavDashboard: 'ภาพรวมระบบ',
    adminNavLogs: 'บันทึกกิจกรรม',
    adminNavNovels: 'จัดการนิยาย',
    adminNavUsers: 'จัดการผู้ใช้',
    adminNavWhitelist: 'อีเมลที่อนุญาต',
    adminNavReports: 'รายงานปัญหา',
    adminNavBin: 'ถังขยะระบบ',
    adminNavScrape: 'แปลนิยายใหม่',
    logsPageTitle: 'บันทึกกิจกรรมและการทำงาน (Activity Logs)',
    logsPageDesc: 'ตรวจสอบย้อนหลังว่าใคร ทำอะไร กับข้อมูลใด เมื่อไหร่ และจาก IP ใด',
    logsSearchPlaceholder: 'ค้นหาตามชื่อผู้ใช้, อีเมล, กิจกรรม, IP หรือรายละเอียด...',
    logsFilterAll: 'ทั้งหมด',
    logsFilterAuth: 'เข้าสู่ระบบ / สิทธิ์',
    logsFilterNovels: 'นิยาย',
    logsFilterChapters: 'ตอนนิยาย',
    logsFilterWhitelist: 'Whitelist',
    logsFilterReports: 'รายงานปัญหา',
    logsFilterBin: 'ถังขยะ',
    logsColTime: 'วัน-เวลา',
    logsColUser: 'ผู้กระทำ (User)',
    logsColAction: 'กิจกรรม (Action)',
    logsColDetails: 'รายละเอียด (Details)',
    logsColIp: 'IP Address',
    logsEmpty: 'ยังไม่มีประวัติกิจกรรมในหมวดหมู่นี้',
    logsTotalRecords: 'รายการทั้งหมด',
    logsTodayRecords: 'กิจกรรมวันนี้',
    logsPage: 'หน้า',
    logsOf: 'จาก',
    logsPrev: 'ก่อนหน้า',
    logsNext: 'ถัดไป',
    systemActor: 'ระบบ / ผู้เยี่ยมชม',
    accessDeniedTitle: 'ไม่มีสิทธิ์เข้าถึง',
    accessDeniedMsg: 'คุณไม่มีสิทธิ์เข้าถึงส่วนของผู้ดูแลระบบ (Admin Console) เฉพาะผู้ดูแลระบบเท่านั้น',
  },
  en: {
    // Navigation & General
    appTitle: 'Tnovel',
    appDesc: 'Web Novel Reader & Translator',
    translateNovel: 'Translate',
    bin: 'Trash',
    admin: 'Admin',
    login: 'Log In',
    logout: 'Log Out',
    profile: 'Profile',
    history: 'History',
    bookshelf: 'Bookshelf',
    myBookshelf: 'My Bookshelf',
    library: 'Novel Library',
    home: 'Home',
    online: 'Online',
    offline: 'Offline',
    back: 'Back',
    backToLibrary: 'Back to Library',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    restore: 'Restore',
    permanentDelete: 'Delete Permanently',
    loading: 'Loading...',
    guest: 'Guest',
    chapterPrefix: 'Chapter',

    // Themes & Language Switcher
    themeLabel: 'Current theme: ',
    themeDark: 'Dark',
    themeLight: 'Light',
    themeSepia: 'Sepia',
    switchToEn: 'Switch to English',
    switchToTh: 'Switch to Thai',

    // Homepage
    heroBadge: 'AI Literary Translation Engine',
    heroTitle: 'Web Novel Translation',
    heroDesc: 'Scrape English web novels and transform them into Thai literary prose. Smooth reading via Mobile PWA with offline caching.',
    searchPlaceholder: 'Search titles or authors...',
    latestNovels: 'Latest Novels',
    recentReadingTitle: 'Continue Reading',
    recentReadingCount: 'novels',
    noRecentReading: 'No recent reading history',
    btnContinueReadingShort: 'Continue',
    scrollLeft: 'Scroll left',
    scrollRight: 'Scroll right',
    loadingNovels: 'Loading library...',
    loadingNovelsSub: 'Please wait, fetching novel list',
    connectingLibrary: 'Connecting to library...',
    connectingLibrarySub: 'Connecting to system, please wait',
    noNovels: 'No novels in library',
    noNovelsDesc: 'Click "+ Translate" button above to paste a URL and start translating English novels into Thai!',
    readNow: 'Read Now',
    noChapters: 'No chapters',
    chaptersCount: 'chs',
    author: 'Author',
    unknownAuthor: 'Unknown Author',
    loadingMore: 'Loading more novels...',
    allNovelsLoaded: 'All novels loaded',
    selectCategory: 'Select Novel Category (Required)*',
    categoryLabel: 'Novel Category',
    categoryRequiredNotice: 'Please select a novel category before translating',
    allCategories: 'All Categories',

    // Novel Card
    translating: 'Translating...',
    moveToBin: 'Move to Trash',
    confirmMoveToBinTitle: 'Move Novel to Trash',
    confirmMoveToBinMsg: 'Are you sure you want to move this novel and all its chapters to the recycle bin? (You can restore it anytime in the recycle bin)',
    addedBy: 'Added by:',
    addedByTitle: 'Added by: ',
    authorTitle: 'Author: ',
    viewCountTitle: 'Views: ',
    timesUnit: ' views',
    fromTotal: ' of ',
    inBookshelfTooltip: 'In bookshelf (click to remove)',
    addToBookshelfTooltip: 'Add to bookshelf',
    likedTooltip: 'Unlike',
    likeTooltip: 'Like',

    // Novel Detail Page
    novelDetailPageTitle: 'Novel Details & Index',
    startReadingFirstChapter: 'Start Reading',
    readFirstChapter: 'Read Chapter 1',
    continueReadingChapter: 'Continue Reading',
    continueReadingFrom: 'Continue from',
    novelSynopsis: 'Synopsis',
    noSynopsis: 'No synopsis available for this novel.',
    readMoreSynopsis: 'Read more',
    readLessSynopsis: 'Show less',
    novelInfo: 'Novel Details',
    sortOldestFirst: 'Oldest First',
    sortNewestFirst: 'Newest First',
    totalChaptersInNovel: 'Total Chapters',
    sourceOriginal: 'Original Source',
    viewOriginalSource: 'View Original Source',
    shareNovel: 'Share',
    copiedLinkToast: 'Link copied to clipboard',
    statusTranslating: 'Translating',
    publishedDate: 'Added on',
    lastUpdatedDate: 'Last updated',
    tableOfContentsForNovel: 'Table of Contents',
    filterChaptersPlaceholder: 'Search by chapter number or title...',
    noChaptersFoundFilter: 'No matching chapters found',
    lastReadBadge: 'Last Read',
    shareNovelSuccess: 'Shared successfully',
    backToHome: 'Back to Home',
    chaptersInNovelCount: 'chapters',

    // Bin (Recycle Bin)
    recycleBinTitle: 'Recycle Bin',
    recycleBinDesc: 'Soft-deleted items. You can restore them or permanently delete them here.',
    viewList: 'List',
    viewCard: 'Card',
    selectAll: 'Select All',
    deselectAll: 'Deselect All',
    selectedItemsCount: 'Selected',
    itemsUnit: 'items',
    restoreSelected: 'Restore Selected',
    permanentDeleteSelected: 'Delete Selected',
    emptyBin: 'Trash is empty',
    emptyBinDesc: 'No novels or chapters in trash.',
    novelsInBin: 'Deleted Novels',
    chaptersInBin: 'Deleted Chapters',
    novelStoryPrefix: 'Novel:',

    // Confirmation Modals
    confirmPermanentDeleteSingleTitle: 'Permanent Delete',
    confirmPermanentDeleteSingleMsg: 'Warning: This will permanently delete this item. It cannot be recovered. Are you sure?',
    confirmPermanentDeleteBatchTitle: 'Delete Selected Items',
    confirmPermanentDeleteBatchMsg: 'Warning: You are about to permanently delete all selected items. This cannot be undone. Are you sure?',
    confirmDeleteButton: 'Confirm Permanent Delete',
    confirmModalSoftDeleteTitle: 'Confirm Move to Trash',
    confirmModalSoftDeleteMsg: 'Are you sure you want to move this item to the trash? You can restore it anytime from the recycle bin.',
    confirmModalSoftDeleteNote: 'This is a soft delete, items can be restored.',

    // Scrape Drawer
    drawerTitle: 'Translate / Import New Novel',
    drawerDesc: 'Paste table-of-contents or chapter URL (Dek-D, RoyalRoad, FanMTL, etc.) to scrape and import.',
    urlInputLabel: 'Source Novel URL',
    urlPlaceholder: 'e.g. https://www.royalroad.com/... or https://writer.dek-d.com/...',
    modeAuto: 'Auto Detect (Recommended)',
    modeSingle: 'Translate/Import Single Chapter',
    modeFull: 'Full Novel (Batch Background)',
    startTranslation: 'Start Scraping & Importing',
    translatingState: 'Translating / Importing content...',
    drawerAddNovel: 'Add / Import Novel',
    drawerTabUrlSub: 'Scrape from novel URL (Dek-D, RoyalRoad, FanMTL, etc.)',
    drawerTabPasteSub: 'Paste copied chapter content (Thai & English supported)',
    tabFromUrl: 'From URL',
    tabPasteSelf: 'Paste Text',
    statusDone: 'Completed',
    pasteNovelTitleLabel: 'Novel Title',
    pasteNovelTitlePlaceholder: 'Select existing or type new novel title',
    pasteNovelTitleHint: 'Matching existing title = appends as next chapter',
    pasteChapterTitleLabel: 'Chapter Title (Optional)',
    pasteChapterTitlePlaceholder: 'e.g. Chapter 1: ... or ตอนที่ 1',
    pasteContentLabel: 'Original Content (Thai & English supported)',
    pasteContentPlaceholder: 'Paste chapter content here, separated by blank lines',
    charCount: 'characters',
    noContentYet: 'No content yet',
    thaiDetectedNotice: '🇹🇭 Thai text detected: direct import without machine translation',
    btnTranslateAndSave: 'Import / Translate & Save',
    scrapeModeLabel: 'Scrape Mode',
    scrapeFullNovel: 'Scrape Full Novel from Index',
    scrapeSingleChapter: 'Scrape Single Chapter',
    translationQualityLabel: 'Translation Quality',
    qualityFast: 'Fast (Google Translate)',
    qualityFastDesc: 'Very fast (~1-2s per chapter)',
    qualityPolished: 'High Quality (Google + AI Polish)',
    qualityPolishedDesc: 'Natural literary Thai prose',
    scrapeUrlInputLabel: 'Novel Index URL or Chapter URL',
    btnStartScrapeAndTranslate: 'Start Scraping & Importing',
    sampleUrlsLabel: 'Sample novel links to try:',
    sampleFullTitle: 'RoyalRoad Index (Full Novel)',
    sampleDekDTitle: 'Dek-D (Thai Full Novel)',
    sampleSingleTitle: 'Single Chapter',

    // History Page
    historyTitle: 'Translation History',
    historySubTitle: 'Novels imported and translated with AI',
    historyDesc: 'Manage imported novels, check translation status, and resume translating remaining chapters.',
    btnTranslateNew: 'Translate New',
    filterAll: 'All',
    filterTranslating: 'Translating / Paused',
    filterCompleted: 'Completed',
    historySearchPlaceholder: 'Search title / author...',
    historyLoading: 'Loading translation history...',
    historyEmpty: 'No translation history found',
    historyEmptyTranslating: 'No novels currently translating or paused',
    historyEmptyCompleted: 'No fully translated novels yet',
    historyEmptyAll: 'You have not imported any novels yet',
    btnStartFirstNovel: 'Translate Your First Novel',
    statusCompleted: 'Fully Translated',
    statusPaused: 'Paused / Ready to Resume',
    translatedCountLabel: 'Translated: ',
    resumeTranslateTooltip: 'Resume scraping and translating remaining chapters',
    btnResume: 'Resume',
    btnReadNovel: 'Read',
    openOriginalWebTooltip: 'Open original website',
    resumeError: 'Failed to resume translation',

    // Bookshelf Page
    bookshelfSyncAccount: 'Synced with your account',
    bookshelfGuestMode: 'Local mode (Saved on this device)',
    tabFollowing: 'Following',
    tabReadingHistory: 'Reading History',
    tabBookmarks: 'Bookmarks',
    bookshelfLoading: 'Loading bookshelf data...',
    bookshelfEmpty: 'No novels in bookshelf yet',
    bookshelfEmptyDesc: 'Click bookmark icon on any novel card to add to bookshelf and track updates.',
    btnBrowseNovels: 'Browse Novels',
    newChaptersNotice: 'New chapters: ',
    removeFromBookshelfTooltip: 'Remove from bookshelf',
    notStartedReading: 'Not started reading',
    totalChaptersLabel: 'Total ',
    btnContinueReading: 'Continue Reading',
    btnStartFirstChapter: 'Start First Chapter',
    noTranslatedChaptersYet: 'No translated chapters yet',
    historyTabDesc: 'Showing novels you have read, ordered by recent',
    btnClearHistory: 'Clear All History',
    historyEmptyTitle: 'No reading history yet',
    historyEmptyDesc: 'When you read any chapter, your progress will be saved here automatically.',
    readUpTo: 'Read up to ',
    readPercent: 'Read ',
    deleteFromHistoryTooltip: 'Remove from history',
    btnReadContinue: 'Continue',
    bookmarksTabDesc: 'Chapters you bookmarked to return to important parts anytime.',
    bookmarksEmptyTitle: 'No bookmarks yet',
    bookmarksEmptyDesc: 'While reading, click settings ⚙️ and select "Bookmark this chapter" to save it here.',
    bookmarkedAt: 'Bookmarked ',
    removeBookmarkTooltip: 'Remove bookmark',
    btnOpenChapter: 'Read Chapter',
    timeJustNow: 'just now',
    timeMinsAgo: 'mins ago',
    timeHoursAgo: 'hours ago',
    timeDaysAgo: 'days ago',

    // Reader View
    prevChapter: 'Previous Chapter',
    nextChapter: 'Next Chapter',
    tableOfContents: 'Table of Contents',
    selectChapterFromTocTooltip: 'Select chapter from table of contents',
    checkNewChapter: 'Check New Chapter',
    checkNewChapterTooltip: 'Check for latest chapters',
    newChapterToastReady: 'Ready to read now',
    newChapterToastDone: 'translated!',
    tocTitle: 'Table of Contents',
    searchChapterPlaceholder: 'Search by chapter number or title...',
    chapterNotFound: 'Chapter not found',
    noChaptersInSystem: 'No chapters in system yet',
    currentlyReading: 'Reading',
    readerSettingsTitle: 'Reader Settings',
    displayModeLabel: 'Display Language',
    modeThLabel: 'Thai (TH)',
    modeEnLabel: 'English (EN)',
    modeParallelLabel: 'Bilingual',
    themeColorLabel: 'Reading Theme',
    themeLightLabel: 'Light (White)',
    themeSepiaLabel: 'Sepia',
    themeDarkLabel: 'Dark (OLED)',
    fontSizeLabel: 'Font Size',
    fontSm: 'Small (14px)',
    fontMd: 'Medium (16px)',
    fontLg: 'Large (18px)',
    fontXl: 'Extra Large',
    fontFamilyLabel: 'Font Family',
    fontSans: 'Sans Serif (Kanit)',
    fontSerif: 'Serif (Sarabun)',
    chapterToolsLabel: 'Chapter Tools',
    retranslateGoogle: 'Retranslate (Google)',
    retranslateGoogleDesc: 'Fast, unlimited',
    polishWithAI: 'AI Literary Polish',
    polishWithAIDesc: 'Refine the Thai into literary prose',
    bookmarkCurrentChapter: 'Bookmark this chapter',
    bookmarkedCurrentChapter: 'Bookmarked (Click to remove)',
    reportChapterIssue: 'Report issue with this chapter',
    noPrevChapter: 'No previous chapter',
    noNextChapter: 'No next chapter',
    autoLoadingNextChapter: 'Auto-loading next chapter...',
    reachedLatestChapter: 'You have reached the latest chapter in the system',
    closeMenu: 'Close Menu',
    retranslatedGoogleSuccess: 'Retranslated with Google Translate',
    polishSuccess: 'Chapter polished successfully',
    polishPartial: 'Partly polished (AI quota ran out), try again later',
    alreadyPolished: 'This chapter is already polished',
    retranslateFailed: 'Retranslation failed',

    // Bookshelf Toasts & Prompts
    historyItemRemovedToast: 'Removed item from history',
    confirmClearHistoryMsg: 'Are you sure you want to clear all reading history?',
    historyClearedToast: 'Reading history cleared',
    bookmarkRemovedToast: 'Bookmark removed',

    // Report Modal
    reportModalTitle: 'Report Issue',
    reportModalSub: 'Report errors to Admin',
    reportSuccessTitle: 'Report submitted successfully',
    reportSuccessDesc: 'Thank you for reporting. The team will inspect it shortly.',
    reportReasonLabel: 'Reason for issue',
    reportDescLabel: 'Additional Details (Optional)',
    reportDescPlaceholder: 'Specify paragraphs or translation errors...',
    reportSending: 'Submitting...',
    reportSubmit: 'Submit Report',
    reportReason1: 'Translation error / Unintelligible',
    reportReason2: 'Mixed English / Incomplete translation',
    reportReason3: 'Chapter incomplete / Missing content',
    reportReason4: 'Source link broken / Inaccessible',
    reportReason5: 'Other issues',
    reportErrorDefault: 'Failed to submit report',
    networkError: 'Cannot connect to server',

    // Background Progress Widget
    widgetPaused: 'Paused',
    widgetResume: 'Resume',
    widgetPause: 'Pause',
    widgetClickToResume: 'Click to resume',
    widgetClickToPause: 'Click to pause',
    widgetMinimize: 'Minimize',
    widgetCancel: 'Cancel Translation',
    widgetCompleted: 'Translation completed!',
    widgetPausedBadge: '⏸️ Translation Paused',
    widgetSavedCount: 'Saved ',
    widgetScanCount: 'Scanned ',
    widgetCancelConfirmTitle: 'Confirm cancel translation?',
    widgetCancelConfirmMsg: 'Are you sure you want to cancel translation of',
    widgetCancelTip: '💡 Already translated chapters are preserved and can be resumed anytime from "Translation History"',
    widgetConfirmCancelBtn: 'Confirm Cancel Translation',
    widgetResumeBackBtn: 'Resume / Go Back',

    // Bin Page
    viewListTooltip: 'List View',
    viewCardTooltip: 'Card View',
    clearSelectionTooltip: 'Clear Selection',
    restoreSingleTooltip: 'Restore',
    permanentDeleteSingleTooltip: 'Permanently Delete',
    restoreSuccess: 'Restored successfully',
    restoreError: 'Error restoring items',
    permanentDeleteSuccess: 'Permanently deleted',
    permanentDeleteError: 'Error permanently deleting items',
    loadingBinItems: 'Fetching items in recycle bin...',
    connectionError: 'Connection error: ',

    // Author & Reader & Profile & Auth
    authorNotFound: 'Author not found',
    authorWorksCount: 'Works in system: ',
    authorAllWorks: 'All works by this author',
    authorNoNovels: 'No novels found for this author',
    loadingNovelContent: 'Loading novel content...',
    loadChapterError: 'Failed to load chapter',
    tryAgain: 'Try again',
    appStatusPwa: 'App Status: Mobile PWA Ready for Offline',
    loginTitle: 'Log In to Tnovel',
    loginSubtitle: 'Read and translate English web novels into Thai literature',
    loginWithGoogle: 'Log in with Google',
    orDivider: 'OR',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    nameLabel: 'Display Name',
    namePlaceholder: 'Your name',
    passwordPlaceholder: 'At least 6 characters',
    loggingIn: 'Logging in...',
    noAccountYet: 'Don\'t have an account yet?',
    registerHere: 'Register here',
    registerTitle: 'Create New Account',
    registerSubtitle: 'Create an account to save reading history and translations',
    continueWithGoogle: 'Continue with Google',
    registering: 'Creating account...',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Log in here',
    authAlertTitle: 'System Notification',
    authErrorTitle: 'Authentication Error',
    btnUnderstand: 'OK',
    adminDashboard: 'Admin Dashboard',

    // Scraper Drawer Statuses & Messages
    scrapeStatusCrawling: 'Scanning and indexing all chapter links from main page...',
    scrapeStatusFetching: 'Fetching content from source novel website...',
    scrapeStatusTranslating: 'Analyzing and translating chapter...',
    scrapeStatusTranslatingBatchesPrefix: 'Translating paragraph batch ',
    scrapeStatusTranslatingBgPrefix: 'Translating in background chapter ',
    scrapeStatusComplete: 'All chapters translated successfully!',
    scrapeStatusRedirecting: 'Translation complete! Redirecting to reader...',
    scrapeStatusInit: 'Initializing scraping system...',
    scrapeErrorServerDb: 'Server error, please check the database',
    scrapeErrorStatusCode: 'Error code ',
    scrapeSuccessRedirecting: 'Done! Redirecting to novel reader...',
    scrapeErrorFetch: 'Error fetching novel content',
    scrapeStatusPasting: 'Translating pasted content...',
    scrapeErrorServer: 'Server connection error',
    scrapeSuccessPasted: 'Translated ',
    scrapeSuccessPastedTail: ' paragraphs. Opening reader...',
    scrapeErrorAddChapter: 'Error adding chapter',

    // Admin Dashboard
    adminPageTitle: 'Admin Dashboard',
    adminPageDesc: 'Manage users, library novels, and user bug reports',
    socketConnected: 'Connected',
    socketDisconnected: 'Disconnected',
    adminTabReports: 'Reports',
    adminTabNovels: 'Manage Novels',
    adminTabUsers: 'Manage Users',
    adminTabWhitelist: 'Allowed Emails (Whitelist)',
    adminLoading: 'Loading Admin data...',
    statusLabel: 'Status:',
    filterPending: 'Pending',
    filterResolved: 'Resolved',
    filterDismissed: 'Dismissed',
    refresh: 'Refresh',
    noReportsTitle: 'No reports in this category',
    noReportsDesc: 'System running smoothly, no user reports submitted',
    reportLocationLabel: 'Problem Location:',
    generalNovel: 'General Novel',
    viewThisChapter: 'View this chapter',
    reportUserDetailLabel: 'Details from user:',
    noDescriptionProvided: 'No additional description provided',
    reportedBy: 'Reported by: ',
    markAsResolved: 'Mark as Resolved',
    dismissReport: 'Dismiss',
    deleteReportTooltip: 'Delete this report',
    originalWebsite: 'Original Website',
    statusInBin: 'In Trash',
    statusActive: 'Active',
    moveToBinTooltip: 'Move to Trash',
    usersListTitle: 'System Users List',
    userColNameEmail: 'Name / Email',
    userColRole: 'Role',
    userColNovelsTranslated: 'Novels Translated',
    userColRegisteredDate: 'Registered Date',
    userColManageRole: 'Manage Role',
    userNoName: 'No Name',
    updating: 'Updating...',
    demoteToUser: 'Demote to USER',
    promoteToAdmin: 'Promote to ADMIN',
    addWhitelistTitle: 'Add Allowed Email (Whitelist)',
    addWhitelistDesc: 'Only emails on this whitelist can log in or register (including Google Login)',
    emailWhitelistPlaceholder: 'user@example.com or user@gmail.com',
    emailNoteLabel: 'Note (Optional)',
    emailNotePlaceholder: 'e.g. backup account, team member, friend',
    addEmailBtn: 'Add Email',
    whitelistListTitle: 'Allowed Emails List',
    searchWhitelistPlaceholder: 'Search email or note...',
    whitelistNotFound: 'No emails matched your search',
    whitelistEmpty: 'No emails in Whitelist yet',
    whitelistColEmail: 'Allowed Email',
    whitelistColNote: 'Note',
    whitelistColRole: 'Role',
    whitelistColAccountStatus: 'System Account Status',
    whitelistColDate: 'Allowed Date',
    whitelistColAction: 'Manage',
    noNote: '- None -',
    hasAccount: 'Has Account',
    notLoggedInYet: 'Not logged in yet',
    primaryAdmin: 'Primary Admin',
    removeFromWhitelistTooltip: 'Remove from Whitelist (Block)',
    whitelistAddSuccess: 'Added email to Whitelist successfully',
    whitelistAddError: 'Failed to add email',
    cannotDeletePrimaryAdmin: 'Cannot delete the primary administrator email',
    confirmDeleteWhitelistMsg: 'Are you sure you want to remove this email from Whitelist? (This user will no longer be able to log in)',
    deleteWhitelistError: 'Error deleting email',
    thNovel: 'Novel',
    thAuthor: 'Author',
    thChaptersCount: 'Chapters',
    thReports: 'Reports',
    thStatus: 'Status',
    thAction: 'Action',
    reportsUnit: 'reports',
    storiesUnit: 'novels',
    adminConsole: 'Admin Console',
    adminBackToSite: 'Back to Website',
    adminNavDashboard: 'Dashboard',
    adminNavLogs: 'Activity Logs',
    adminNavNovels: 'Novels',
    adminNavUsers: 'Users',
    adminNavWhitelist: 'Whitelist',
    adminNavReports: 'Reports',
    adminNavBin: 'Recycle Bin',
    adminNavScrape: 'Translate Novel',
    logsPageTitle: 'Activity & Audit Logs',
    logsPageDesc: 'Track who did what, when, and from which IP address',
    logsSearchPlaceholder: 'Search by user, email, action, IP or details...',
    logsFilterAll: 'All',
    logsFilterAuth: 'Auth & Accounts',
    logsFilterNovels: 'Novels',
    logsFilterChapters: 'Chapters',
    logsFilterWhitelist: 'Whitelist',
    logsFilterReports: 'Reports',
    logsFilterBin: 'Recycle Bin',
    logsColTime: 'Timestamp',
    logsColUser: 'Actor',
    logsColAction: 'Action',
    logsColDetails: 'Details',
    logsColIp: 'IP Address',
    logsEmpty: 'No activity logs found in this category',
    logsTotalRecords: 'total logs',
    logsTodayRecords: 'today',
    logsPage: 'Page',
    logsOf: 'of',
    logsPrev: 'Previous',
    logsNext: 'Next',
    systemActor: 'System / Guest',
    accessDeniedTitle: 'Access Denied',
    accessDeniedMsg: 'You do not have permission to access the Admin Console. Admin privileges required.',
  },
} as const;

export type TranslationKey = keyof typeof languages.th;
